---

- name: fix asadmin
  replace:
    path: "{{ glassfish_home }}/glassfish{{ glassfish_major_version }}/bin/asadmin"
    regexp: ^AS_INSTALL=.*$
    replace: AS_INSTALL="$(dirname "$("${READLINK_PATH:-readlink}" -f "$0")")/../glassfish"
    backup: yes
  become_user: glassfish
  become: yes

- name: create bin symlinks
  file:
    src: "{{ glassfish_home }}/glassfish{{ glassfish_major_version }}/bin/{{ item }}"
    dest: /usr/local/bin/glassfish-{{ item }}
    state: link
    force: yes
  with_items:
    - asadmin
    - pkg
    - updatetool
  become: yes

- name: install domain libs
  get_url:
    url: "{{ item }}"
    dest: "{{ glassfish_home }}/glassfish{{ glassfish_major_version }}/glassfish/domains/domain1/lib"
  with_items: "{{ glassfish_domain_libs }}"
  become_user: glassfish
  become: yes
  when: glassfish_domain_libs | length > 0
  notify: restart_glassfish
